###
GET http://localhost:3000/api/users/0850dfa7-91fb-4cbd-82f6-579c63bd5316
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiMDg1MGRmYTctOTFmYi00Y2JkLTgyZjYtNTc5YzYzYmQ1MzE2IiwidXNlcm5hbWUiOiJrc21pZ2llbHNraSIsIm1haWwiOiJrYW1pbC5zbWlnaWVsc2tpQG91dGxvb2suY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkTERPM0VZZkhRVmpvUVFVeWJkeG5vLkJFNkV5VDc2TS40Y2tXU2hyckJMWkp3VGJJREtKb2UiLCJ2ZXJpZmllZCI6ImZhbHNlIiwiaWF0IjoxNzE4MDUwNTM1LCJleHAiOjE3MTgwNTQxMzV9.RtKiBWOwXUN06VBPLVXzsMWmuTBc7j80TzhC3jYDYT8