###
GET http://localhost:3000/api/filters/metadata/206fcc9b-f8d7-450b-aed7-594c57d7fcc6

###
PATCH http://localhost:3000/api/filters
Content-Type: 'application/json'

{
    "id":"3309e351-6bed-4fe6-8e5f-84a5f7746968",
    "filter":"tint"
}
### GET - current image
GET http://localhost:3000/api/getImage/b8aae216-cd48-423e-a837-5b4aa2267d5e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTIxZDhhMDItNmRiNy00ZWU1LThiZWQtOTJjZjAwMjdhYjc1IiwidXNlcm5hbWUiOiJrc21pZ2llbHNraSIsIm1haWwiOiJrYW1pbEBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDRZY3lJWnZlWFg5Sy9PNmlEbTBOb2V6ZG13TDV5dTUycG1ZU2VENWZjeGJ1Skc1T1B2UGxxIiwidmVyaWZpZWQiOiJmYWxzZSIsImlhdCI6MTcxNzk2MTUxNiwiZXhwIjoxNzE3OTY1MTE2fQ.g5G1F1DaLEqyz6rdFbzBVH-hzXueAS6us5RmsrgaIBM

### GET - original image
GET http://localhost:3000/api/getImage/original/3309e351-6bed-4fe6-8e5f-84a5f7746968
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNTIxZDhhMDItNmRiNy00ZWU1LThiZWQtOTJjZjAwMjdhYjc1IiwidXNlcm5hbWUiOiJrc21pZ2llbHNraSIsIm1haWwiOiJrYW1pbEBtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDRZY3lJWnZlWFg5Sy9PNmlEbTBOb2V6ZG13TDV5dTUycG1ZU2VENWZjeGJ1Skc1T1B2UGxxIiwidmVyaWZpZWQiOiJmYWxzZSIsImlhdCI6MTcxNzk2MTM5NSwiZXhwIjoxNzE3OTY0OTk1fQ.MJCd29iWeztaVtYRS-1dz


### GET - filtered image
GET http://localhost:3000/api/getImage/invert/3309e351-6bed-4fe6-8e5f-84a5f7746968