### GET - index
GET http://localhost:3000 HTTP/1.1

### POST - upload photo
#   Done
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.png"
Content-Type: image/png

< ./input.png

------FormBoundary1234
Content-Disposition: form-data; name="album"

test_album
------FormBoundary1234

### GET - get json of all items
#   Done
GET http://localhost:3000/api/photos HTTP/1.1

### GET - get json of item
#   Done
GET http://localhost:3000/api/photos/b60c03e5-0094-41a8-b63a-6989b583c5b7 HTTP/1.1

### DELETE - delete file
# Done
DELETE http://localhost:3000/api/photos/e2115122-5bae-4bfa-8fab-f89aeb89076c HTTP/1.1

### PATCH - update
PATCH  http://localhost:3000/api/photos/b60c03e5-0094-41a8-b63a-6989b583c5b7 HTTP/1.1